### ISSUE TITLE
关于系统设计部分

### ISSUE THREAD

**Issue by orikey0** [conanhujinming/tips_for_interview#3]
关于这部分内容，请问老大当时是基于什么样的资料或者说是方式来进行学习的呢，实在是好奇，业务场景一直在变，究竟什么才是设计一个系统的核心。

**Comment by conanhujinming** [comment]
说实话，我没特意准备过。不过根据我个人经验，一些好的系统课程，如15-213, CS162, 6.828, 6.824都会讲一些系统设计的重要思想，有些还会带你去读一些经典论文。有一些方法和思想是通用的，例如cache, multi-stage, batch, pipeline, chunk, locality, index等等，还有一些是为场景特地设计的。总得来说，我个人认为设计一个系统的核心就是要结合通用的思想与具体的场景问题。
